In [3]:
%matplotlib inline

In [34]:
import numpy as np
from scipy.spatial import Delaunay, Voronoi
import k3d


points = np.array([[-1,-1,-1],[-1,-1,1],[-1,1,-1],[1,-1,-1],[1,1,1],[1,1,-1],[1,-1,1],[-1,1,1],[0,0.5,0]])

tri = Delaunay(points, qhull_options = 'Qt Qbb Qc').simplices

#discar flat tetrahedron
keep = np.ones(len(tri), dtype = bool)
for i, t in enumerate(tri):
    if abs(np.linalg.det(np.hstack((points[t], np.ones([1,3+1]).T)))) < 1E-15:
        keep[i] = False # Point is coplanar, we don't want to keep it
tri = tri[keep]

print (tri)

#flatten vertices list
vertices = [p for pt in points for p in pt]

#triangulate tetrahedron
indices = [[t[0],t[1],t[2],t[0],t[1],t[3],t[0],t[2],t[3],t[1],t[2],t[3]] for t in tri]

#flatten triangle indices
indices = [t for tri in indices for t in tri]

plot = k3d.plot()
plot += k3d.mesh(vertices, indices, wireframe=True)
plot.display()


[[5 8 3 0]
 [5 8 2 0]
 [6 8 3 0]
 [6 8 1 0]
 [6 5 8 3]
 [6 5 4 8]
 [7 8 2 0]
 [7 8 1 0]
 [7 5 8 2]
 [7 5 4 8]
 [7 6 8 1]
 [7 6 4 8]]


Output()